version: "3.0"

services:
  web:
    env_file: ./web/.env
    image: "${IMAGE_WEB}"
    ports:
      - "3000:3000"
    volumes:
      - /web

  cdn-server:
    env_file: ./cdn-server/.env
    image: "${IMAGE_CDN_SERVER}"
    ports:
      - "8090:8090"
    volumes:
      - /cdn-server

  api:
    env_file: ./api/.env
    image: "${IMAGE_API}"
    ports:
      - "8080:8080"
    volumes:
      - /api

  angelica:
    env_file: ./angelica/.env
    image: "${IMAGE_ANGELICA}"
    ports:
      - "8040:8040"
    volumes:
      - /angelica

  iframe-server:
    env_file: ./iframe-server/.env
    image: "${IMAGE_IFRAME_SERVER}"
    volumes:
      - /iframe-server
    ports:
      - "8010:8010"

  mav:
    env_file: ./mav/.env
    image: "${IMAGE_MAV}"
    ports:
      - "8020:8020"
    volumes:
      - /mav

  watcher:
    env_file: ./watcher/.env
    image: "${IMAGE_WATCHER}"
    ports:
      - "8000:8000"
    volumes:
      - /watcher

  # logger:
  #   env_file: ./logger/.env
  #   image: "${IMAGE_LOGGER}"
  #   ports:
  #     - "8022:8022"
  #   volumes:
  #     - /logger

  # mongodb:
  #   image: mongo
  #   ports:
  #     - "27017:27017"
  #   # volumes:
  #   #   - mongodb:/data/db
  #   environment:
  #     - MONGO_INITDB_DATABASE=ada-application-core

volumes:
  api:
  angelica:
  watcher:
  cdn-server:
  web:
  iframe-server:
  # logger:
