#cloud-config

groups:
  - hashicorp
  - ubuntu: [root, sys]

users:
  - default
  - name: terraform
    gecos: terraform
    shell: /bin/bash
    primary_group: hashicorp
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: false
    ssh_authorized_keys:

cloud_final_modules:
  - rightscale_userdata
  - scripts-per-once
  - scripts-per-boot
  - scripts-per-instance
  - [scripts-user, always]
  - keys-to-console
  - phone-home
  - final-message

runcmd:
  - sudo su terraform
  - sudo chown -R terraform:hashicorp /home/terraform
  - chmod +x /home/terraform/build/boot.sh
bootcmd:
  - bash /home/terraform/build/boot.sh
