version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  api:
    docker:
      - image: circleci/node:12.0.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "api/package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run:
          command: cd api && npm install && npm test
      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules
          key: node-v1-{{ .Branch }}-{{ checksum "api/package-lock.json" }}
      - codecov/upload:
          file: "./api/coverage/clover.xml"
  angelica:
    docker:
      - image: jeffmendez19/puppateer-node-light
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "angelica/package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run:
          command: cd angelica && npm install && npm test
      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules
          key: node-v1-{{ .Branch }}-{{ checksum "angelica/package-lock.json" }}
      - codecov/upload:
          file: "./angelica/coverage/clover.xml"
  mav:
    docker:
      - image: jeffmendez19/tensorflow-node-gpu
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "mav/package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run:
          command: cd mav && npm install && npm test
      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules
          key: node-v1-{{ .Branch }}-{{ checksum "mav/package-lock.json" }}
      - codecov/upload:
          file: "./codecov.yml"
      - codecov/upload:
          file: "./mav/coverage/clover.xml"
  web:
    docker:
      - image: circleci/node:14.3.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "web/package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run:
          command: cd web && npm install && npm test
      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules
          key: node-v1-{{ .Branch }}-{{ checksum "web/package-lock.json" }}
      - codecov/upload:
          file: "./web/coverage/clover.xml"
  iframe-server:
    docker:
      - image: circleci/node:14.3.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "iframe-server/package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run:
          command: cd iframe-server && npm install && npm test
      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules
          key: node-v1-{{ .Branch }}-{{ checksum "iframe-server/package-lock.json" }}
      - codecov/upload:
          file: "./iframe-server/coverage/clover.xml"
  cdn-server:
    docker:
      - image: circleci/node:14.3.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "cdn-server/package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run:
          command: cd cdn-server && npm install && npm test
      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules
          key: node-v1-{{ .Branch }}-{{ checksum "cdn-server/package-lock.json" }}
      - codecov/upload:
          file: "./cdn-server/coverage/clover.xml"
workflows:
  build_and_test:
    jobs:
      - api
      - mav
      - angelica
      - web
      - iframe-server
      - cdn-server
