version: 2.1
jobs:
  angelica:
    docker:
      - image: jeffmendez19/puppateer-node-light
    steps:
      - checkout
      - run:
          command: cd angelica && npm install && npm test
  mav:
    docker:
      - image: circleci/node:14.3.0
    steps:
      - checkout
      - run:
          command: cd mav && npm install && npm test
  web:
    docker:
      - image: circleci/node:12.0.0
    steps:
      - checkout
      - run:
          command: cd web && npm install && npm test
  iframe-server:
    docker:
      - image: circleci/node:current
    steps:
      - checkout
      - run:
          command: cd iframe-server && npm install && npm test
  cdn-server:
    docker:
      - image: circleci/node:current
    steps:
      - checkout
      - run:
          command: cd cdn-server && npm install && npm test
workflows:
  build_and_test:
    jobs:
      - mav
      - angelica
      - web
      - iframe-server
      - cdn-server
