version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  api:
    docker:
      - image: circleci/node:12.0.0
    steps:
      - checkout
      - run:
          command: cd api && npm install && npm test
      - codecov/upload:
          file: "./codecov.yml"
  angelica:
    docker:
      - image: jeffmendez19/puppateer-node-light
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "angelica/package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run:
          command: cd angelica && npm install && npm test
      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules
          key: node-v1-{{ .Branch }}-{{ checksum "angelica/package-lock.json" }}
  mav:
    docker:
      - image: circleci/node:14.3.0
    steps:
      - checkout
      - run:
          command: cd mav && npm install && npm test
      - codecov/upload:
          file: "./codecov.yml"
  web:
    docker:
      - image: circleci/node:12.0.0
    steps:
      - checkout
      - run:
          command: cd web && npm install && npm test
  iframe-server:
    docker:
      - image: circleci/node:current
    steps:
      - checkout
      - run:
          command: cd iframe-server && npm install && npm test
  cdn-server:
    docker:
      - image: circleci/node:current
    steps:
      - checkout
      - run:
          command: cd cdn-server && npm install && npm test
      - codecov/upload:
          file: "./codecov.yml"
workflows:
  build_and_test:
    jobs:
      - api
      - mav
      - angelica
      - web
      - iframe-server
      - cdn-server
