export const CLEAR_MODELS = "CLEARED AI MODELS";
export const LOADED_MODELS = "MODELS ALREADY LOADED";
export const LOADING_MODELS = "LOADING AI MODELS";

export const LOADING_MOBILE_NET = "LOADING MOBILENET MODEL";
export const LOADING_COCOA_SSD = "LOADING COCOASSD MODEL";
