export const row: string
export const hide: string
export const hidden: string
export const mainFixed: string
export const fixedFrame: string
export const mainFrame: string
export const main: string
export const mainInput: string
export const outerSpace: string
