export const row: string
export const hide: string
export const alignCenter: string
export const tipType: string
export const fixes: string
export const absolute: string
export const reccList: string
export const dark: string
export const light: string
export const mainButton: string
