FROM node:12.10.0-alpine

WORKDIR /usr/src/app/

COPY package*.json bootstrap.sh *.key ./

RUN apk upgrade --update-cache --available && \
	apk add openssl && \
	rm -rf /var/cache/apk/*

RUN npm run bootstrap && npm ci

COPY . .

CMD [ "npm", "run", "dev" ]
