name: Benches
on:
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: "off"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install the CLI
        run: |
          cargo install  --path ./cli --force
      - name: Run Benchmarks
        run: cd benchmarks && cargo bench
