FROM node:12.0.0-alpine AS BUILD_IMAGE

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

FROM node:12.0.0-alpine

WORKDIR /usr/src/app

# copy from build image
COPY --from=BUILD_IMAGE /usr/src/app/src ./src
COPY --from=BUILD_IMAGE /usr/src/app/node_modules ./node_modules
COPY --from=BUILD_IMAGE /usr/src/app/package.json ./package.json
COPY --from=BUILD_IMAGE /usr/src/app/package-lock.json ./package-lock.json
COPY --from=BUILD_IMAGE /usr/src/app/tsconfig.json ./tsconfig.json
COPY --from=BUILD_IMAGE /usr/src/app/.env ./.env
COPY --from=BUILD_IMAGE /usr/src/app/nodemon.json ./nodemon.json

CMD [ "yarn", "dev"]