FROM node:14.7.0-alpine

WORKDIR /usr/src/app 

COPY package*.json .env ./

RUN apk --no-cache add --virtual native-deps \
	g++ gcc libgcc libstdc++ linux-headers make python && \
	npm install --quiet node-gyp -g &&\
	npm install --quiet && \
	apk del native-deps

COPY . .

CMD [ "TS_NODE_PROJECT=tsconfig.server.json", "ts-node", "./server/server.ts" ]
