FROM mhart/alpine-node:14

WORKDIR /app

COPY package*.json ./

RUN npm ci

FROM mhart/alpine-node:slim-14

WORKDIR /usr/src/app

COPY --from=0 /app .
COPY . .

CMD ["node_modules/next/dist/bin/next", "dev"]